# Generated by Django 3.0.1 on 2020-01-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='upload',
            field=models.FileField(upload_to='music'),
        ),
    ]
