# Generated by Django 3.0.14 on 2021-04-14 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0008_chordcounter'),
        ('uploads', '0004_auto_20210414_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='task',
            field=models.ForeignKey(default=1111, on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.TaskResult', to_field='task_id'),
            preserve_default=False,
        ),
    ]
